### PR TITLE
Update CONTRIBUTORS

### PR DESCRIPTION
**Pull request by Hypercubed**
Added hypercubed to contributors

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Same here, update with master, and you're good to go ;)

**Comment by Hypercubed** [comment]
Are you able to squash and merge these through GH?

**Comment by tannerlinsley** [comment]
Yeah, if you'd rather have them squashed, I can do that.  Cleaner Commits vs. More Commits on your end.

**Comment by Hypercubed** [comment]
Would be nice to squash out the merged master branch comments.

**Pull request merged**
