### PR TITLE
Convert tests to AVA

### PR DESCRIPTION
**Pull request by Hypercubed**

### CODE REVIEW

**Comment by Hypercubed** [comment]
Tests are failing because of the old version of reductio which expects `crossfilter` to be defined globally (I think).  Bumping to the latest reductio fixes this but then causes the "funky failures" discussed on gitter.

**Comment by Hypercubed** [comment]
Once https://github.com/crossfilter/reductio/pull/42 is accepted we can bump reductio to latest and tests will pass.

**Comment by Hypercubed** [comment]
All tests are passing now with the latest reductio.

**Comment by tannerlinsley** [comment]
Nice job

**Pull request merged**
