### PR TITLE
Chore/lint

### PR DESCRIPTION
**Pull request by Hypercubed**
I added XO and fixed all reasonable linting errors.  I commented out variables that were unused and temporarily changed some errors to warnings.  Maybe before merging we can decide on the following rules:

- [quotes](http://eslint.org/docs/rules/quotes): single or double
- [comma-dangle](http://eslint.org/docs/rules/no-comma-dangle): always or never
- [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren): always or never

I know it looks like a scary amount of changes, sorry.

### CODE REVIEW

**Comment by Hypercubed** [comment]
My suggestion is the xo defaults:

Single quotes, no comma dangle, and space before function parens.   This would also improve your code climate score.

**Comment by tannerlinsley** [comment]
I am good with that, minus the dangle.

**Comment by Hypercubed** [comment]
The default is to enforce no comma dangle.  To confirm, you would like to enforce the comma dangle?  Or allow either way?

**Comment by tannerlinsley** [comment]
Force comma dangle

**Comment by Hypercubed** [comment]
Ok, I updated the quotes and function parens rule, and fixed source and test files.  For my own sanity, I disable the comma dangle rule for now.

**Pull request merged**
